services:
  server:
    build:
      context: .
      target: build
      args:
        - HUGO_ENV=production
        - DOCS_URL=http://docs.iechor.com
    ports:
      - "1313:1313"
    entrypoint:
      ["hugo", "server", "--bind", "0.0.0.0", "--environment", "production","-b","http://docs.iechor.com"]
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
